name: noteit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_staggered_grid_view: '0.3.0'

  avatar_glow: ^1.2.0
  speech_to_text: ^2.3.0

  intl: ^0.16.1
  
  uuid: ^2.0.4
  path_provider: ^1.6.0
  flutter_image_compress: ^0.6.5+1
  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.2

  url_launcher: ^5.5.3

  material_design_icons_flutter: ^4.0.5655

  firebase_auth: ^0.15.4
  google_sign_in: ^4.0.1+1
  cloud_firestore: ^0.13.1
  firebase_storage: ^3.1.1

  provider: ^4.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

